security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_TESTER:      ROLE_USER
        ROLE_MODO:        ROLE_TESTER
        ROLE_ADMIN:       ROLE_MODO

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous:    true
            logout:       
                path: fos_user_security_logout
                target: fos_user_security_login
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                default_target_path: fos_user_profile_show

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/compte, roles: ROLE_USER }
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }